name: Branch Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement (main, prod, qual, dev)'
        required: true
        default : 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v4.1.1

      - name: Echo for Prod
        if: github.event.inputs.environment == 'prod'
        run: echo "prod"

      - name: Echo for Qual
        if: github.event.inputs.environment == 'qual'
        run: echo "qual"

      - name: Echo for Dev
        if: github.event.inputs.environment == 'dev'
        run: echo "dev"

      - name: Exit
        run : exit 1

      - name : Last
        if: always()
        run: echo end
